# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Scrape Endorsements

on:
  workflow_dispatch:
    # https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: franzdiebold/github-env-vars-action@v1.0.0
      # https://github.com/marketplace/actions/github-environment-variables-action
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run scrape --if-present
      env:
          ENV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
